tests/config.py
getpass does not need a TTY and is the recommended way according to
the python documentation.
=> Use getpass.getuser() instead of os.getlogin()

tests/conftest.py, tests/lib/hardware.py, tests/lib/kubernetes.py, tests/test_node_addition.py
Use a base class to abstract the methods a hardware class needs to
have. The former hardware class has now only libcloud OpenStack
specific code inside.
Also prefix some methods with _ to mark it as private methods.
=> tests/lib/hardware: Create HardwareBase class

tests/lib/hardware.py
Commit 617dc5a688dd did refactor some stuff and renamed libcloud_conn
to conn. One place was not renamed. Fixed now.
=> tests/lib/hardware: Fix unknown libcloud_conn var

tests/lib/ansible_helper.py, tests/lib/hardware.py
Moving ansible related code into its own file (and out of the hardware
releated code) makes the code more structured.
=> tests/lib/ansible_helper: Move ansible code to extra file

tests/conftest.py, tests/lib/hardware/base.py, tests/lib/hardware/openstack_libcloud.py
Move the base class to its own file and the OpenStack libcloud
implementation to it's own file. That way, it's easier to write new
hardware backends.
=> tests/lib/hardware: Restructure hardware related code

tests/lib/hardware/base.py, tests/lib/hardware/openstack_libcloud.py
_image_cache and _size_cache are unrelated to base but an
implementation detail of the libcloud implementation. So move the
variables there.
=> tests/lib/hardware/base: Move base unrelated vars

tests/lib/hardware/base.py, tests/lib/hardware/openstack_libcloud.py
Make it clear which interface can be used outside of
hardware. Currently this is only the node name and get_ssh_ip().
=> tests/lib/hardware: Create NodeBase class

tests/lib/hardware/openstack_libcloud.py
Commit bdb377028916a did add that method to the base class but forgot
to drop the method in the openstack-libcloud implementation.
=> tests/lib/hardware: Drop ansible_inventory_vars

tests/lib/ansible_helper.py, tests/lib/hardware/base.py, tests/lib/hardware/openstack_libcloud.py
That's useful for static code checking.
Also move private_key to the base class. That's an error that mypy
detected.
=> Add some basic type hints for mypy

tests/lib/ansible_helper.py, tests/lib/hardware/hardware_base.py, tests/lib/hardware/node_base.py, tests/lib/hardware/openstack_libcloud.py
Commit 769b54c8e76126f6 introduced a circular import. Resolve this by
moving the hardware and node base classes into extra files.
=> tests/lib: Resolve circular import

tests/lib/kubernetes.py
Commit bdb377028916ad1 removed the private marker for get_ssh_ip(). So
fix it when using the method.
=> tests/lib/kubernetes: Fix get_ssh_ip() call

tests/conftest.py, tests/lib/ansible_helper.py, tests/lib/hardware/hardware_base.py, tests/lib/hardware/openstack_libcloud.py, tests/lib/kubernetes.py, tests/lib/rook.py, tox.ini
Instead of doing prints, use logging to log messages. That way, we can
have different log levels and more control over the output in general.
=> Use python logging module

tests/conftest.py, tests/lib/kubernetes/kubernetes_base.py, tests/lib/kubernetes/vanilla.py
Create a abstract base class for kubernetes called KubernetesBase. The
common methods/properties are defined in that class.
Then create a Vanilla class which implements the KubernetesBase class.
=> tests/lib/kubernetes: Restructure kubernetes abstraction

tests/lib/hardware/hardware_base.py, tests/lib/hardware/openstack_libcloud.py
The methods are only internally used and should not be used outside.
=> tests/lib/hardware: Mark more methods as private

tests/lib/hardware/hardware_base.py
- Do output the hardware uuid and the working directory during
initializing the hardware. That makes debugging easier where the
working directory for the hardware is usually needed.
- Fix log output when adding a node to the hardware.
=> tests/lib/hardware/hardware_base: Improve logging

tests/lib/hardware/hardware_base.py, tests/lib/hardware/openstack_libcloud.py, tests/lib/kubernetes/vanilla.py, tests/lib/rook.py
Provide more detail in logging for when Ansible fails (or a node is
unreachable). Also returns the successful nodes in a run for extra
information.
This reduces the duplication of error catching for running playbooks.
=> Automatically output Ansible result dictionary on failure

tests/lib/hardware/openstack_libcloud.py
Try to find a free IP to associate in existing pool.
Fallback to creating one if necessary.
Reason:
I faced issues when testing where allocating new IP was not possible due to full pool, though a lot of unassociated ones where laying aroung.
=> Try to associate IP when possible rather than allocating

tests/lib/ansible_helper.py
In case somebody runs tox from an unexpected dir.
=> Use absolute path for raw ansible playbooks

tests/lib/kubernetes/caasp.py
When using CaaSP as k8s deployment mechanism, the kubectl binary is
not downloaded. Instead we assume that the binary is available on the
local machine. So use the correct path (instead of something in the
workspace dir).
=> kubernetes/caasp: Fix kubectl path

tests/conftest.py, tests/lib/rook/base.py, tests/lib/rook/upstream.py
This PR aims to structure rook code as it was done for kubernetes
The RookBase class is inherited by various implementation of
rook (upstream, ses etc...) and imported as RookCluster
=> Add more structure rook code

doc/source/development_notes.rst, tests/conftest.py, tests/lib/hardware/hardware_base.py, tests/lib/kubernetes/caasp.py, tests/lib/kubernetes/kubernetes_base.py, tests/lib/kubernetes/vanilla.py
Mark the method get_node_by_role() as private given that it should
only be used internally. Then also drop the get_masters() and
get_workers() functions and just add properties for master and
worker.
That's what is used in the end and in the caasp implementation, there
is no longer a need to call get_masters() and get_workers().
=> hardware/hardware_base: Add masters and workers properties

README.rst
Link rook.io for easier navigation. Also drop the libcloud
requirement. There are already 2 implementations (libcloud and
libvirt).
=> README: Link rook, drop libcloud requirement

tests/lib/common.py, tests/lib/hardware/hardware_base.py, tests/lib/hardware/libvirt.py, tests/lib/hardware/openstack_libcloud.py, tests/lib/kubernetes/caasp.py, tests/lib/kubernetes/kubernetes_base.py, tests/lib/kubernetes/vanilla.py, tests/lib/rook.py, tests/lib/workspace.py, tests/test_utils.py
This greatly improves the readability of a test run.
The only output should be via the logger*. The log level is controlled by pytest.
Only log things that are useful.
* The exception is Ansible which is still using sys.stdout. This will need revisiting, but I'm considering reworking Ansible into using `ansible-playbook` instead of the unsupported python api.
=> Better execution and logging

tox.ini
This turned out to be usefull when trying libvirt backend with
qemu+ssh:// style URL where you sometime want to reuse an existing
password protected key already added to the agent
=> Allow usage of existing SSH Agent

tests/config.py, tests/lib/ansible_helper.py, tests/lib/hardware/libvirt.py, tests/lib/workspace.py
Having the date in the cluster prefix makes it easier to find outdated
workspace dirs. Also rename "rookci" to "rookcheck" to make it clear
where the tmp dir is coming from.
Note: This just changes the default. A user can still change the
behavior with setting CLUSTER_PREFIX.
=> tests/config: Add date to default cluster prefix and rename default

tests/test_fixtures.py
We don't need to build an expensive rook cluster to make sure fixtures
are behaving how we expect. Instead use the workspace fixture.
We also don't need the debug test that was leftover from manual testing.
Also fix up the logging/output of the tests.
=> Tidy up test_fixtures

tests/lib/ansible_helper.py, tests/lib/hardware/hardware_base.py, tests/lib/workspace.py
Instead of having the basic ansible variables (eg. private key, host
key checking, workspace dir, ...) in the hardware base class, move
theses to the workspace class.
That's logical given that the variables used there are defined in the
Workspace class anyway.
This also simplifies the variables that need to be passed into the
ansible executor methods.
=> workspace: Move basic ansible inventory vars to workspace

tests/assets/ansible/roles/node-base/tasks/main.yml, tests/assets/ansible/roles/node-base/tasks/opensuse_leap-15.yml
Before doing anything on a openSUSE 15 node, make sure the basic
repositories are set up.
=> node-base/tasks/opensuse_leap-15: Add basic repos

tests/lib/hardware/hardware_base.py, tests/test_fixtures.py
It's needed when a extra node is added during a test and the node
needs to be prepared. With the new "limit_to_nodes" parameter, this
can be done.
Also fix the test and add the "prepare_nodes()" call with a single
node.
=> hardware/hardware_base: Add limit option to prepare_nodes()

tests/lib/hardware/libvirt.py, tests/lib/hardware/node_base.py, tests/lib/hardware/openstack_libcloud.py
Rook does not deploy properly without dedicated data disk (i.e
using a folder as a fake 'data holder'). This is at least the case
for SES rook.
This PR add a function to add disks to node. The size defaults to
10G as of now but this should be improved by allowing both the
disk number and size to be specified as global test variables.
=> Add a function to add disks

tests/assets/ansible/playbook_node_base.yml, tests/assets/ansible/roles/node-base/tasks/main.yml
The gather_facts itself can fail before wait_for_connection is
executed. That leads to an unreachable node and the following error:
fatal: [rookcheck-tom-20200605-66ad_worker_1]: UNREACHABLE! => \
{"changed": false, "msg": "Failed to connect to the host via ssh: \
ssh: connect to host 10.86.6.110 port 22: No route to host", \
"unreachable": true}
No gathering facts before waiting solves that problem.
=> roles/node-base: Do not gather facts when waiting for nodes

tests/config.py, tests/conftest.py, tests/lib/hardware/hardware_base.py, tests/lib/hardware/libvirt.py, tests/lib/hardware/openstack_libcloud.py
Set default worker nodes to 3.
In a cluster it makes more sense to default to 3 nodes for
quorum reasons usually.
This also harmonize boot_nodes() call between all implementation.
fixes #94
=> Add env parameters for number of masters/workers.

tox.ini
That's needed when sourcing a env config file and then running
tox. Otherwise, the configuration values are not recognized.
=> tox.ini: Pass ENVVAR_PREFIX_FOR_DYNACONF into tox env

tests/assets/ansible/roles/caasp/tasks/Suse.yaml
Until a more advanced repo switching solution is available
we stick to test released version of Caasp4
=> Update repo to use Caasp 4 on SLE15SP1

tests/assets/ansible/roles/kubernetes_vanilla/tasks/common.yaml
When the apparmor service is not available, don't do
anything. Otherwise the role fails while trying to stop the service.
This fixes:
Could not find the requested service apparmor: host
=> ansible/roles/kubernetes_vanilla: Fix stop/disable apparmor

tests/lib/rook/upstream.py
Restoring the directory is unnecessary since the commands execute in a
subprocess. Also the "pushd && git checkout && popd" fail on some systems
Signed-off-by: Eric Jackson <swiftgist@gmail.com>
=> Execute cd and git checkout

tests/lib/rook/upstream.py
This ensures the tmpdir is created.
Fixes #119
=> Fix tmpdir for go build

tests/assets/ansible/roles/rook/tasks/sles-15.yml, tests/lib/rook/ses.py
Use SES6 while waiting for a proper solution for selecting
version to be released.
Storage repo had most likely been erased during a merge.
=> Fix SES deployment

tests/assets/ansible/roles/node-base/tasks/sles-15.yml
It turns out that kernel-default-base is causing conflicts during
skuba package update (which is using zypper)
This commit simply remove the conflicting and now unused package.
=> Remove kernel-default-base

tests/assets/ansible/roles/node-base/tasks/sles-15.yml, tests/lib/kubernetes/caasp.py
Skuba is returning "joined the cluster" before the nodes are actually
marked ready.
This commit introduces a wait for all nodes to be marked as ready.
It also add a 5s wait after that step so that skuba/zypper can release
package management lock.
Also add update of all packages in early steps because otherwise skuba
does it on its own, and the wait indicated above is more hardly
predictable. Updating at the start makes it more predictable and having
the system up to date is better anyway.
=> Wait for Caasp to be ready

.travis.yml, bindep.txt, test-requirements.txt
If it's not installed, the LIBVIRT hardware provider just
fails. That's confusing for newcomers.
The downside is that libvirt-devel needs to be installed locally (but
that's already in the bindep file)
Fixes: #116
=> test-requirements: Install libvirt-python

tests/conftest.py, tests/lib/rook/base.py, tests/lib/rook/ses.py, tests/lib/rook/upstream.py
This adds build/preinstall/install steps to both implementation.
Having a build() method is necessary in ses (though is does nothing
usefull) so we can call it early in threaded tests that will
opportunitely build rook if possible before deployment.
Move install code to base class as it is no upstream specific.
Move ceph features method (rbd, fs...) to base class too.
=> Structure ses/rook upstream the same way

tests/assets/ansible/roles/caasp/files/skuba-update, tests/assets/ansible/roles/caasp/tasks/Suse.yaml
Skuba package does install a timer that triggers skuba-update program at
specific time to handle intelligent updates of running CaaSP clusters.
This is not a feature we want in rookcheck context.
=> Set skuba to annotate only mode

tests/assets/ansible/roles/caasp/tasks/Suse.yaml, tests/lib/kubernetes/caasp.py
Install skuba on first master and retrieve it into workspace.
This should ensure that skuba version matches CaaSP as they are
installed from the same repo.
=> Add skuba builtin support

tests/lib/common.py
Rookcheck waits for 3 nodes to have OSD's prepared before continuing.
However, there is a race condition where the 4th node might come up before
the check is done causing the check to fail.
Instead the regex_count_matcher should search for a minimum amount of
matches.
=> Fix race condition with counting ready containers

.gitignore, Jenkinsfile.integration, config/rook_upstream.toml, config/settings.toml, tests/lib/rook/upstream.py
This will add a Jenkins.integration file which is a Jenkins
pipeline. That file can be used to test PRs against rookcheck.
=> Jenkinsfile.integration: Add basic jenkins run

tests/lib/kubernetes/vanilla.py, tests/test_check_num_osd.py
This test adds a new worker node to the compute cluster and afterwards also to Kubernetes itself.
It tests if rook automatically discovers the node as also the new disk and if rook automatically starts a new osd-pod for this new "machine".
=> Test for autodiscovery of new node and new disks in Rook

tests/lib/rook/base.py
Ignore any OSD containers on the master.
=> Wait for the workers to have their OSD's prepared

tests/lib/kubernetes/kubernetes_base.py, tests/test_services.py
This tests is a starting point for all rook-services.
It includes in this first step checks to test if all basic services are up and running and that the RGW service gets started automatically as soon as an ObjectStore gets created
=> This test checks if all services are up and running

tests/lib/rook/base.py, tests/test_check_num_osd.py, tests/test_storage_addition.py
This test adds a new storage device to an existing node and checks if rook adds it automatically to the ceph-cluster.
=> Test auto-discovery of new storage devices 

tests/lib/kubernetes/kubernetes_base.py, tests/lib/rook/base.py, tests/test_mons.py
This test checks if the configured amount of monitor-services and -pods are up and running.
=> Test to check if all monitor-services and monitor-pods are up

bindep.txt, test-requirements.txt
See https://dmsimard.com/2016/01/08/selinux-python-virtualenv-chroot-and-ansible-dont-play-nice/
=> Add in selinux requirement to help with redhat distros

config/settings.toml, tests/assets/ansible/roles/caasp/tasks/Suse.yaml, tests/assets/ansible/roles/node_base/defaults/main.yaml, tests/assets/ansible/roles/node_base/tasks/opensuse_leap-15.yml, tests/assets/ansible/roles/node_base/tasks/sles-15.yml, tests/assets/ansible/roles/rook/tasks/sles-15.1.yml, tests/assets/ansible/roles/rook/tasks/sles-15.2.yml, tests/lib/hardware/hardware_base.py
In order to pass custom repo (but that could be anything), you used
to have to update yaml repo definition.
This PR allows you to easily pass vars to ansible by setting an
env variable ROOKCHECK_ANSIBLE_EXTRA_VARS:
export ROOKCHECK_ANSIBLE_EXTRA_VARS='{"repo":{"storage_latest": "http://download.suse.de/ibs/SUSE:/SLE-15-SP2:/Update:/Products:/SES7/images/repo/SUSE-Enterprise-Storage-7-POOL-x86_64-Media1/"}}'
repo var was renamed to _repo within ansible playbook to avoid
conflicts during lookup
=> Allow passing extra-vars to ansible

config/libvirt.toml, config/openstack.toml, examples/libvirt-caasp-ses.env, examples/libvirt-k8s-upstream.env, examples/openstack-k8s-upstream.env
openSUSE 15.2 got released some time ago. Use that by default instead
of 15.1.
=> config & examples: Switch to openSUSE 15.2

tests/lib/rook/base.py, tests/test_basic.py
* First we make sure the expected (default) number of MON pods are running
* We increase the number of expected MON pods by 2, allowing more than one MON pods per node
* We make sure the new expected number of MON pods are all running
* Finally, we decrease the number of MON pods down to the default number, also disallowing more than one MON pods per node
=> Add test for increasing/decreasing the number of active MON pods

tests/lib/hardware/libvirt.py
With cache=none, I'm getting an error like:
libvirt: QEMU Driver error : internal error: \
qemu unexpectedly closed the monitor: [...] file system may \
not support O_DIRECT
This happens on an ext4 filesystem. Switching to a
different cache mode solves the problem.
=> hardware/libvirt: Change qemu cache mode to writeback

examples/libvirt-caasp-ses.env
We need to install CaaSP on top of SLE. openSUSE won't work.
=> examples/libvirt-caasp-ses: Use SLE15SP1 image instead of openSUSE

tests/config.py, tests/test_playground.py
It's needed to have the libvirt variables available when using the
libvirt backend. Otherwise it fails with:
dynaconf.vendor.box.exceptions.BoxKeyError: "'DynaBox' object has \
no attribute 'network_range'"
=> config: Include libvirt.toml config

tests/lib/hardware/aws_ec2.py, tests/lib/hardware/libvirt.py, tests/lib/hardware/node_base.py, tests/lib/hardware/openstack_sdk.py
Create an abstract disk_create() method in the HardwareBase
class. That way, it's clear that this method expects an int for the
disk capacity in GB.
This also fixes the disk deployment for libvirt where
test_add_storage() test failed because the rook-discover pod didn't
use the newly created disk (due to "Insufficient space (\u003c5GB)").
The extra qcow2 disk that was created for libvirt had a size of 512
byte.
=> lib/hardware: Unify and abstract disk_create method

tests/lib/rook/base.py
After the OSDs got created, we currently used directly the
rook-ceph-tools container to check the ceph cluster status.
That might fail with:
error: unable to upgrade connection: container not \
found ("rook-ceph-tools")
in the case container is not yet running. So wait for the
rook-ceph-tools container before checking the cluster status.
=> rook/base: Wait for rook-ceph-tools container before using it

tox.ini
That can be done via the -rA options. See [1]
[1]
https://docs.pytest.org/en/latest/usage.html#detailed-summary-report
=> tox: Add summary report at the end of a pytest run

Jenkinsfile.integration
Do create junit test results with pytest and also collect then so
Jenkins can show nice graphs for the different tests.
=> Jenkinsfile.integration: Create and collect junit results

tests/lib/rook/base.py
For understanding problems with test cases, it's usually useful to
have more information from the rook operator. So set the log level to
DEBUG.
Also do not unconditionally wait 10 seconds but instead wait for the
operator to be running.
=> rook/base: Set rook operator log level to debug and wait for it

tests/test_basic.py
Apparently it takes a very long time to settle (5-10min) to a lower
number of mons. I'm not sure why. This is possibly just k8s deciding
when a good time is  do an acount. Nevertheless, give this a bit more
room to move.
=> Increase the amount of time to wait for mon changes

Jenkinsfile.integration
That's useful for the junit output to have more data about the test
environment.
=> Jenkinsfile.integration: set junit suite name to differ between the test envs

config/settings.toml, doc/source/usage.rst, tests/conftest.py, tests/lib/hardware/aws_ec2.py, tests/lib/hardware/hardware_base.py, tests/lib/hardware/libvirt.py, tests/lib/hardware/openstack_sdk.py, tests/lib/kubernetes/kubernetes_base.py, tests/lib/rook/base.py, tests/lib/workspace.py
Add option to leave cluster available after run
By default the cluster is destroyed at each run. This adds a new option
(_tear_down_cluster) which can be set to False to keep the cluster around.
This also tidies up the removal of AWS nodes which can use the super
class's method to destroy them instead of repeating the code.
=> Add option to leave cluster available after run

tests/lib/rook/base.py
This will speedup the discovery of new devices.
=> rook/base: Reduce ROOK_DISCOVER_DEVICES_INTERVAL to 2m

tests/lib/common.py, tests/lib/hardware/hardware_base.py, tests/lib/kubernetes/kubernetes_base.py, tests/lib/rook/base.py, tests/lib/workspace.py
Add the possibility to go into the python debugger (pdb) to be able to
look further into the problem.
=> Improve TEAR_DOWN_CLUSTER_CONFIRM handling

tests/assets/ansible/roles/node_base/tasks/sles-15.yml
Using waitsync is necessary on an existing machine to avoid
disrupting services by a too quick adjustment.
In the CI contexty of setting up new machines, this is a waste of
time (as much as 150s just for chronyc waitsync)
=> Sync time using NTP immediate command

tests/lib/kubernetes/kubernetes_base.py, tests/lib/rook/base.py
That way, the logs show more from the real command without wasting
space for the --namespace argument.
Eg.
07:06:41 kubectl --namespace rook-ceph get pod -l app=
will then show more.
=> Use -n instead of --namespace for kubectl

tests/lib/rook/upstream.py
While updatting PR, a chdir() context change was forgottent,
leading to a failure when building from GIT.
This PR fixes taht by using workspace.execute() and its chdir
parameter.
=> Fix upstream build from git

tests/lib/hardware/libvirt.py
On some version of libvirt the "Duplicate key" internal error occurs
while trying to define a node in parallel, for example:
Traceback (most recent call last):
File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/usr/lib64/python3.6/threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File "/home/kyr/suse/rookcheck/tests/lib/hardware/libvirt.py", line 400, in _boot_node
node = self.node_create(name, role, tags)
File "/home/kyr/suse/rookcheck/tests/lib/hardware/libvirt.py", line 396, in node_create
node.boot()
File "/home/kyr/suse/rookcheck/tests/lib/hardware/libvirt.py", line 75, in boot
self._dom = self._conn.defineXML(xml)
File "/home/kyr/suse/rookcheck/.tox/py36/lib64/python3.6/site-packages/libvirt.py", line 4049, in defineXML …
=> hardware/libvirt: add lock for libvirt defineXML

config/settings.toml, tests/lib/hardware/hardware_base.py
Instead of merging settings.ANSIBLE_EXTRA_VARS with the variable
"extra_vars" provided by ansible_run_playbook(), decouple both
variables. That way, extra_vars (the method parameter) can be set from
the code (eg. the SES rook code) and settings.ANSIBLE_EXTRA_VARS can
be set by the user and it can be something independent (eg. a file
@foo.yaml).
=> hardware_base: Decouple ANSIBLE_EXTRA_VARS settings

tests/config.py
Since moving to Dynaconf v3 we lost automatic loading of .env files.
https://www.dynaconf.com/release_notes/#load-of-dotenv-env-is-now-disabled-by-default
=> Restore support for loading .env files

Jenkinsfile.integration
Include build number in cluster prefix for PR triggered jobs.
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>
=> Jenkinsfile.integration: add build number to cluster prefix

tests/lib/hardware/hardware_base.py
This PR fixes a concatenation issue ending up in having
--extra-vars to be empty.
Looks like the += syntax with "f" strings needs an explicit
multiline indication to concatenate properly.
=> Fix passing ANSIBLE_EXTRA_VARS

tests/lib/common.py
This PR fixes a bug where wait_for_result() would exit immediately
if the called function raises an error.
We now catch the exception until max attempts is reached.
=> Ensure wait_for_result really does wait

tests/lib/common.py
The wait_for_result was not correctly incrementing its counter
causing rookcheck to get stuck.
=> Fix counting attempts in helper function

config/openstack.toml, tests/lib/rook/base.py, tests/test_basic.py
The tests were previously passing because we weren't correctly
failing once a timeout reached. Now that we are failing we are hitting
these timeouts. So bump them for now.
(Also fix up a default in a config file)
=> Bump general timeouts due to slow ECP

Jenkinsfile.integration, config/ses.toml
Previously it was using the published chart instead of devel.
=> Use correct devel chart for ses devel7

config/ses.toml, tests/lib/rook/ses.py
This allows us to overwrite helm values using a very simple search
+ replace.
We can't trivially provide a second values.yaml as we don't know the
exact container version numbers.
This should allow us to test SES builds from IBS.
=> Allow substitutions to helm values

tests/lib/rook/base.py
As of Nautilus v14.2.20 and Octopus v15.2.11, clusters intentionally come up in
HEALTH_WARN (AUTH_INSECURE_GLOBAL_ID_RECLAIM) and to achieve HEALTH_OK we have
to disallow this insecure feature.
Signed-off-by: Joshua Hesketh <josh@nitrotech.org>
=> Fix AUTH_INSECURE_GLOBAL_ID_RECLAIM warning

config/ses.toml, tests/lib/rook/base.py, tests/lib/rook/ses.py, tests/lib/rook/upstream.py
We need a later version of helm than what is in SLE 15.2 for OCI support.
=> Use latest helm

config/ses.toml
For our development env we should also ensure to use our dev-containers instead the ones from upstream.
=> Use devel-containers instead of the upstream ones
