- tests/config.py
- tests/lib/distro/base.py
- tests/lib/distro/opensuse.py
- tests/lib/hardware/openstack_libcloud.py
- tests/lib/kubernetes.py
Still a lot more to do here, but this should help me stop conflicting with @toabctl's refactors against my local branch ;-)
> Small refactor for different base distros

- doc/source/conf.py
- doc/source/index.rst
- tox.ini
Generated via sphinx-quickstart. That will be useful to document more
things in the future.
> docs: Add basic sphinx doc structure

- LICENSE
- tests/config.py
- tests/conftest.py
- tests/lib/ansible_helper.py
- tests/lib/common.py
- tests/lib/distro/base.py
- tests/lib/distro/opensuse.py
- tests/lib/hardware/hardware_base.py
- tests/lib/hardware/node_base.py
- tests/lib/hardware/openstack_libcloud.py
- tests/lib/kubernetes.py
- tests/lib/rook.py
- tests/test_basic.py
- tests/test_fixtures.py
- tests/test_node_addition.py
This is to match rook's license.
Signed-off-by: Joshua Hesketh <josh@nitrotech.org>
(Also signed off by Thomas Bechtold <tbechtold@suse.com> through amended commit)
> Change license to apache2

- tests/lib/hardware/hardware_base.py
- tests/lib/hardware/openstack_libcloud.py
The ssh host key needs to be removed for mitogen in all
implementations. So move the removal from the OpenStack libcloud
implementation to the HardwareBase class and do the removal when a new
Node is added.
> tests/lib/hardware: Move ssh host key removal to HardwareBase

- tests/config.py
- tests/conftest.py
- tests/lib/ansible_helper.py
- tests/lib/common.py
- tests/lib/hardware/hardware_base.py
- tests/lib/hardware/libvirt.py
- tests/lib/hardware/openstack_libcloud.py
- tests/lib/kubernetes/caasp.py
- tests/lib/kubernetes/kubernetes_base.py
- tests/lib/kubernetes/vanilla.py
- tests/lib/rook.py
- tests/lib/workspace.py
- tests/test_basic.py
Add a workspace fixture to decouple working dirs from the hardware classes.
> Workspace improvements

- bindep.txt
- doc/source/installation.rst
- tests/config.py
- tests/lib/ansible_helper.py
- tests/lib/hardware/hardware_base.py
- tests/lib/hardware/libvirt.py
- tests/lib/hardware/openstack_libcloud.py
- tests/lib/kubernetes/caasp.py
- tests/lib/workspace.py
- tox.ini
The primary tidy up is around AnsibleRunner (see commits).
> General tidy ups

- tests/lib/workspace.py
That way it's more clear what was removed.
> workspace: Log workspace dir name when removing the directory

- tests/lib/ansible_helper.py
- tests/lib/common.py
- tests/lib/hardware/hardware_base.py
- tests/lib/hardware/libvirt.py
- tests/lib/hardware/openstack_libcloud.py
- tests/lib/kubernetes/kubernetes_base.py
- tests/lib/rook/upstream.py
- tests/lib/workspace.py
- tests/test_basic.py
- tests/test_utils.py
test_basic now builds completely and passes on OpenStack for me.
> Various fixes to logging and command execution

- README.rst
- bindep.txt
- doc/source/installation.rst
- tests/config.py
- tests/conftest.py
- tests/lib/hardware/libvirt.py
- tests/lib/hardware/node_base.py
- tests/lib/hardware/openstack_libcloud.py
- tests/lib/workspace.py
> Config fixes

- tests/assets/ansible/playbook_ses.yaml
- tests/assets/ansible/roles/rook/tasks/main.yml
- tests/assets/ansible/roles/rook/tasks/sles-15.yml
- tests/conftest.py
- tests/lib/rook/base.py
- tests/lib/rook/ses.py
- tests/lib/rook/upstream.py
This add SES support.
I did consider that having HEALTH_OK is enough to consider the CEPH cluster functionnal, without further deployment
> Add SES support

- tests/lib/rook/upstream.py
Set TMPDIR to use the workspace_dir setting to consolidate temporary
files
Signed-off-by: Eric Jackson <swiftgist@gmail.com>
> Build rook in workspace_dir

- test-requirements.txt
Config management changed in version 3 so that our code is not
compatible yet.
Ensuring proper version is installed for now.
> Ensure dynaconf version <3.0.0

- config/settings.toml
- tests/lib/hardware/libvirt.py
- tests/lib/hardware/node_base.py
- tests/lib/hardware/openstack_sdk.py
This PR add methods to handle disk management for both current
backends
> Add data disk management (create, attach, detach)

- tests/test_basic.py
This test expects the example filesystem to be installed.
Fixes #142 .
> Fix test_basic

- config/settings.toml
- tests/assets/ansible/roles/caasp/tasks/Suse.yaml
- tests/assets/ansible/roles/rook/tasks/sles-15.1.yml
- tests/assets/ansible/roles/rook/tasks/sles-15.2.yml
- tests/lib/rook/ses.py
This PR adds a way to specify the version of SES you wan't to run.
This is obviously tied to the base OS you're running too.
So this PR also adds support for SLES15SP2
> Add SES_VERSION variable and SES7 support

- config/aws_ec2.toml
- config/settings.toml
- examples/aws_ec2-k8s-upstream.env
- test-requirements.txt
- tests/assets/ansible/roles/node_base/tasks/main.yml
- tests/conftest.py
- tests/lib/hardware/aws_ec2.py
- tests/lib/hardware/node_base.py
- tests/lib/hardware/openstack_sdk.py
- tests/lib/kubernetes/vanilla.py
- tests/test_basic.py
- tests/test_fixtures.py
- tools/clean_openstack_resources.py
This PR adds a driver for AWS.
> Add support for AWS

- bindep.txt
- doc/source/configuration.rst
- doc/source/installation.rst
- tox.ini
> Fixes for recent issues

- tools/clean_openstack_resources.py
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>
> tools: skip cleaning volumes in-use

- tests/conftest.py
To help see what rookcheck thinks is the settings.
> Add some pre-flight checks and debug information

- Jenkinsfile.integration
Use openSUSE 15.2 instead of 15.1 as testing image
> Use openSUSE 15.2

- tests/lib/kubernetes/caasp.py
Simply do any role on the workers for now. Test will need a way
of being more specific in the future.
> Label worker nodes for any rook role

- examples/libvirt-caasp-ses.env
- examples/openstack-caasp-ses.env
- tests/assets/ansible/roles/caasp/tasks/Suse.yaml
Update repos and packages name.
Also ensure zypper does accept the license automatically.
> Add Caasp 4.5 support

- tests/test_basic.py
- tests/test_playground.py
This test was unstable previously. Re-enabling so that we can get some data.
> Re-enable test_add_node

- Jenkinsfile.integration
- config/settings.toml
- tests/conftest.py
- tests/lib/kubernetes/kubernetes_base.py
- tests/lib/workspace.py
This allows us to capture the output of all the containers and kubernetes info which is very useful for debugging.
> Add support to gather logs at end of run

- tests/test_basic.py
This test creates and uses csi/rbd storage.
> CI test: Ceph block (RBD) PVCs

- Jenkinsfile.integration
Uses the RocketChat Notifier jenkins plugin.
> Report results to rocketchat if configured

- tools/clean-libvirt
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>
> tools: add clean libvirt

- tests/test_basic.py
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>
> test_basic::test_add_storage: improve failure reporting

- tox.ini
That makes debugging a bit easier.
> tox: List dynaconf options before running tests

- tests/lib/kubernetes/kubernetes_base.py
- tests/lib/workspace.py
For some reason gathering the logs doesn't always work. This is to help
get more information for why that might be.
> Log exception traceback in gather logs

- config/ses.toml
> Update default SES configuration options for 7.1

- Jenkinsfile.integration
> Only test SES by default

- Jenkinsfile.integration
> Fix default value in jenkins integration

- tests/test_basic.py
This moves the tests more likely to fail to later in the build.
> Reorder tests

- tests/test_basic.py
> Reduce mon test temporarily

- tests/test_basic.py
> Rearrange tests

- tests/test_basic.py
> Rearrange tests and add extra logging

- test-requirements.txt
> pin openstacksdk dep

- config/ses.toml
- tests/test_playground.py
Remove unecessary repos for SES7.1 devel installations
> Add playground with no rook pre-installed

- config/ses.toml
> This particular ceph-version is not available anymore
